### ISSUE TITLE
Receiving error while compiling stylus

### ISSUE THREAD

**Issue by devin6391** [THPubs/LevelupIntermediateMeteor#1]
Getting error: 
app/styles.styl.css:57:6: property missing ':'

Learning meteor with version 1.3.4.1, using stylus. Following your you tube intermediate tutorials.

**Comment by devin6391** [comment]
Error with css minifier only. Without it, works fine

**Comment by THPubs** [comment]
@devin6391 Devin this is not the official repo... I was also following that tutorial and created this. You can check the official repos in here : https://github.com/leveluptuts
